./a < ../problems.pam/1.pam > 1.txt &
./a < ../problems.pam/2.pam > 2.txt &
./a < ../problems.pam/3.pam > 3.txt &
./a < ../problems.pam/4.pam > 4.txt &
./a < ../problems.pam/5.pam > 5.txt &
./a < ../problems.pam/6.pam > 6.txt &
./a < ../problems.pam/7.pam > 7.txt &
./a < ../problems.pam/8.pam > 8.txt &
./a < ../problems.pam/9.pam > 9.txt &
./a < ../problems.pam/10.pam > 10.txt &
./a < ../problems.pam/11.pam > 11.txt &
./a < ../problems.pam/12.pam > 12.txt &
./a < ../problems.pam/13.pam > 13.txt &
./a < ../problems.pam/14.pam > 14.txt &
./a < ../problems.pam/15.pam > 15.txt &
./a < ../problems.pam/16.pam > 16.txt &
./a < ../problems.pam/17.pam > 17.txt &
./a < ../problems.pam/18.pam > 18.txt &
./a < ../problems.pam/19.pam > 19.txt &
./a < ../problems.pam/20.pam > 20.txt &
./a < ../problems.pam/21.pam > 21.txt &
./a < ../problems.pam/22.pam > 22.txt &
./a < ../problems.pam/23.pam > 23.txt &
./a < ../problems.pam/24.pam > 24.txt &
./a < ../problems.pam/25.pam > 25.txt &
