./a.out < ../../problems.pam/1.pam > ../../solutions/1-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/2.pam > ../../solutions/2-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/3.pam > ../../solutions/3-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/4.pam > ../../solutions/4-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/5.pam > ../../solutions/5-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/6.pam > ../../solutions/6-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/7.pam > ../../solutions/7-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/8.pam > ../../solutions/8-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/9.pam > ../../solutions/9-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/10.pam > ../../solutions/10-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/11.pam > ../../solutions/11-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/12.pam > ../../solutions/12-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/13.pam > ../../solutions/13-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/14.pam > ../../solutions/14-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/15.pam > ../../solutions/15-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/16.pam > ../../solutions/16-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/17.pam > ../../solutions/17-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/18.pam > ../../solutions/18-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/19.pam > ../../solutions/19-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/20.pam > ../../solutions/20-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/21.pam > ../../solutions/21-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/22.pam > ../../solutions/22-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/23.pam > ../../solutions/23-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/24.pam > ../../solutions/24-johniel3-$(date +%s).isl &
./a.out < ../../problems.pam/25.pam > ../../solutions/25-johniel3-$(date +%s).isl &
