
build:
	g++ -std=gnu++17 -Wall -Wextra -O2 a.cpp

run: build
	./a.out < ../../problems.pam/1.pam > ../../solutions/1/shiota1-v1.isl
	./a.out < ../../problems.pam/2.pam > ../../solutions/2/shiota1-v1.isl
	./a.out < ../../problems.pam/3.pam > ../../solutions/3/shiota1-v1.isl
	./a.out < ../../problems.pam/4.pam > ../../solutions/4/shiota1-v1.isl
	./a.out < ../../problems.pam/5.pam > ../../solutions/5/shiota1-v1.isl
	./a.out < ../../problems.pam/6.pam > ../../solutions/6/shiota1-v1.isl
	./a.out < ../../problems.pam/7.pam > ../../solutions/7/shiota1-v1.isl
	./a.out < ../../problems.pam/8.pam > ../../solutions/8/shiota1-v1.isl
	./a.out < ../../problems.pam/9.pam > ../../solutions/9/shiota1-v1.isl
	./a.out < ../../problems.pam/10.pam > ../../solutions/10/shiota1-v1.isl
	./a.out < ../../problems.pam/11.pam > ../../solutions/11/shiota1-v1.isl
	./a.out < ../../problems.pam/12.pam > ../../solutions/12/shiota1-v1.isl
	./a.out < ../../problems.pam/13.pam > ../../solutions/13/shiota1-v1.isl
	./a.out < ../../problems.pam/14.pam > ../../solutions/14/shiota1-v1.isl
	./a.out < ../../problems.pam/15.pam > ../../solutions/15/shiota1-v1.isl
